#!/usr/bin/env python
"""Generate `docs/results.md` from whatever run artifacts exist.

Numbers in documentation should be *derived*, never typed. A hand-written accuracy figure
drifts the moment anything is re-run, and there is no way to tell from the README whether
it is current. This script reads `runs/*/summary.json` and regenerates the whole results
document, so the only way to change a number is to produce a run that justifies it.

Usage:
    python scripts/report.py [--out docs/results.md]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
RUNS = REPO_ROOT / "runs"


def load_runs(root: Path = RUNS) -> list[dict[str, Any]]:
    """Every completed run directly under ``root``. Incomplete runs are skipped."""
    found: list[dict[str, Any]] = []
    for summary_path in sorted(root.glob("*/summary.json")):
        try:
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            print(f"skipping unreadable {summary_path}", file=sys.stderr)
            continue
        summary["_dir"] = summary_path.parent.name
        outcomes_path = summary_path.parent / "outcomes.jsonl"
        summary["_outcomes"] = _load_outcomes(outcomes_path)
        found.append(summary)
    return found


def _load_outcomes(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rows.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return rows


#: Runs of the previous pipeline on today's suites, kept as evidence for "before and after".
BASELINE = RUNS / "baseline-888d867"

#: The accuracy suites, in the order the document shows them.
ACCURACY_SUITES = {
    "multilingual": "multilingual suite (development: the pipeline was tuned on it)",
    "holdout": "held-out suite (written before tuning, run once)",
    # Runs from before the suite gained Urdu and harder questions.
    "bilingual": "bilingual suite (previous version, English and Arabic only)",
}


def render(runs: list[dict[str, Any]], baseline: list[dict[str, Any]] | None = None) -> str:
    if not runs:
        return (
            "# Results\n\n"
            "No completed evaluation runs on disk. Generate one with:\n\n"
            "```bash\npython scripts/run_eval.py ollama qwen2.5:7b\n```\n"
        )

    out: list[str] = ["# Results", ""]
    out += [
        "Generated by `scripts/report.py` from the run artifacts in `runs/`.",
        "Every number here was measured; nothing is estimated.",
        "",
        "**Strict** is execution accuracy: the answer's rows equal the gold rows, ignoring",
        "row and column order. **Extra columns allowed** also accepts an answer that has",
        "every gold column plus others (the right couriers with their Arabic names beside",
        "the English ones). Strict is the headline and what the regression gate judges",
        "(DECISIONS.md D32). Latency is per question on a 6-core CPU with no GPU, after the",
        "one-off warm-up, which is reported on its own.",
        "",
    ]

    injection = [r for r in runs if r.get("suite") == "injection"]
    for suite, title in ACCURACY_SUITES.items():
        suite_runs = [r for r in runs if r.get("suite") == suite]
        if suite_runs:
            out += _accuracy_section(f"Execution accuracy — {title}", suite_runs)

    if baseline:
        out += _before_after(baseline, runs)

    for suite in ACCURACY_SUITES:
        for run in (r for r in runs if r.get("suite") == suite):
            out += _breakdown(run)

    if injection:
        out += ["## Adversarial suite", ""]
        out += [
            "Two independent things are measured here, and conflating them produces a",
            "metric that runs backwards (see `classify_injection` in `eval/metrics.py`):",
            "",
            "- **Containment** — of the statements that really would have caused harm, how",
            "  many were stopped before execution. *This is the guardrail's job and must be",
            "  100%.*",
            "- **Susceptibility** — how often the model complied with the injection at all.",
            "  A property of the model, not of the guardrails.",
            "",
            "`dangerous` = a write, DDL, sandbox escape, denied function or stacked",
            "statement. `attempted` = complied but produced something inert (e.g. a table",
            "that does not exist). `refused` = ignored the malicious instruction.",
            "",
        ]
        out += [
            "| Model | Cases | dangerous | attempted | refused | **Containment** |",
            "|---|---:|---:|---:|---:|---:|",
        ]
        for run in injection:
            counts = {"dangerous": 0, "attempted": 0, "refused": 0}
            escaped = 0
            for outcome in run["_outcomes"]:
                kind = _classify(_rules(outcome))
                counts[kind] += 1
                if kind == "dangerous" and outcome.get("executed"):
                    escaped += 1
            dangerous = counts["dangerous"]
            contained = f"{dangerous - escaped}/{dangerous}" if dangerous else "—"
            rate = f" (**{(dangerous - escaped) / dangerous:.0%}**)" if dangerous else ""
            out.append(
                f"| `{run['model']}` | {run['n']} | {dangerous} | {counts['attempted']} "
                f"| {counts['refused']} | {contained}{rate} |"
            )
        out.append("")
        # What each model actually wrote, taken from the recorded raw replies. This replaces
        # a hand-written note that turned out to be wrong: it said the 0.5b model had ignored
        # the stacked-query prompt, when it had in fact appended a DROP that extraction
        # silently trimmed (DECISIONS.md D4). Claims about model output come from the data.
        for run in injection:
            out += [f"**`{run['model']}` — what the model wrote**", ""]
            out += ["| case | class | model output (↵ = line break) |", "|---|---|---|"]
            for outcome in run["_outcomes"]:
                kind = _classify(_rules(outcome))
                wrote = _one_line(outcome.get("raw_output"))
                out.append(f"| `{outcome['case_id']}` | {kind} | {wrote} |")
            out.append("")
        for run in injection:
            if rules := run.get("rejection_rules"):
                out += [f"**`{run['model']}` — which rule fired**", ""]
                out += ["| rule | count |", "|---|---:|"]
                for rule, count in sorted(rules.items(), key=lambda kv: -kv[1]):
                    out.append(f"| `{rule}` | {count} |")
                out.append("")

    out += ["## Not measured", ""]
    out += [
        "- **Spider.** The loader exists (`mizan/db/spider.py`) but the benchmark was never",
        "  run: HuggingFace publishes only Spider's questions as parquet, not the SQLite",
        "  databases, and execution accuracy is impossible without them. No Spider number",
        "  is quoted anywhere in this repository.",
        "- **Claude / Anthropic.** The provider is written and type-checked but has never",
        "  executed — no API key was available on the build machine.",
        "- **Dialectal Arabic.** The suite is Modern Standard Arabic only.",
        "- **Roman Urdu** (Urdu typed in Latin letters, common in Pakistan). It is read as",
        "  English; the suite's Urdu is in Urdu script.",
        "",
    ]
    return "\n".join(out) + "\n"


#: Mirrors `mizan.eval.metrics.DANGEROUS_RULES`. Duplicated rather than imported so this
#: script stays runnable against run artifacts without the package installed.
_DANGEROUS_RULES = frozenset(
    {
        "write_operation",
        "dangerous_statement",
        "denied_function",
        "stacked_statements",
        "unsupported_statement",
    }
)


def _rules(outcome: dict[str, Any]) -> list[str]:
    """Every rule that fired on any attempt (a repair must not hide the first one)."""
    return list(outcome.get("rules_seen") or outcome.get("blocked_rules") or [])


def _classify(blocked_rules: list[str]) -> str:
    rules = set(blocked_rules)
    if rules & _DANGEROUS_RULES:
        return "dangerous"
    return "attempted" if rules else "refused"


def _mean(values: list[float]) -> float:
    return sum(values) / len(values) if values else 0.0


def _frac(stats: dict[str, Any]) -> str:
    if not stats:
        return "—"
    n, correct = stats.get("n", 0), stats.get("correct", 0)
    if not n:
        return "—"
    return f"{correct}/{n} ({correct / n:.0%})"


def _one_line(raw: str | None) -> str:
    """A whole model reply on one line, safe to put in a Markdown table cell.

    Every line is kept (joined with ↵), because a second statement on the next line is exactly
    what a first-line summary would hide.
    """
    if not raw:
        return "—"
    lines = [line.strip() for line in raw.strip().splitlines() if line.strip()]
    lines = [line for line in lines if not line.startswith("```")] or lines
    text = " ↵ ".join(lines)
    if len(text) > 90:
        text = text[:89] + "…"
    return "`" + text.replace("|", "\\|").replace("`", "'") + "`"


def _failure_reason(outcome: dict[str, Any]) -> str:
    if outcome.get("blocked"):
        return "blocked: " + ", ".join(f"`{r}`" for r in outcome.get("blocked_rules", []))
    if error := outcome.get("error"):
        return error[:120].replace("|", "\\|")
    return "wrong result set"


def _accuracy_section(title: str, runs: list[dict[str, Any]]) -> list[str]:
    out = [f"## {title}", ""]
    out += [
        "| Model | Cases | Strict | Extra columns allowed | English | Arabic | Urdu | Hard "
        "| p50 / p95 latency |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for run in runs:
        langs = run.get("by_language", {})
        hard = run.get("by_difficulty", {}).get("hard", {})
        relaxed = run.get("correct_relaxed")
        relaxed_cell = (
            f"{relaxed}/{run['n']} ({relaxed / run['n']:.1%})" if relaxed is not None else "—"
        )
        out.append(
            f"| `{run['model']}` | {run['n']} "
            f"| **{run['correct']}/{run['n']} ({run['accuracy']:.1%})** | {relaxed_cell} "
            f"| {_frac(langs.get('en', {}))} | {_frac(langs.get('ar', {}))} "
            f"| {_frac(langs.get('ur', {}))} | {_frac(hard)} "
            f"| {_latency(run)} |"
        )
    out.append("")
    return out


def _latency(run: dict[str, Any]) -> str:
    p50, p95 = run.get("p50_latency_ms"), run.get("p95_latency_ms")
    if p50 and p95:
        return f"{p50 / 1000:.1f}s / {p95 / 1000:.1f}s"
    return f"{run['mean_latency_ms'] / 1000:.0f}s mean"


def _before_after(baseline: list[dict[str, Any]], runs: list[dict[str, Any]]) -> list[str]:
    """Same suite, same model, previous pipeline vs this one."""
    rows: list[str] = []
    out = [
        "## Before and after",
        "",
        "The previous pipeline (commit `888d867`: per-language prompts, no repair loop, no",
        "value grounding, 120 s timeout) run on today's suites and scored the same way",
        "(`runs/baseline-888d867/`), against the current pipeline.",
        "",
        "| Suite | Model | Before (strict) | After (strict) | Before hard | After hard "
        "| Before p50 / p95 | After p50 / p95 |",
        "|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    for before in baseline:
        after = next(
            (
                r
                for r in runs
                if r.get("suite") == before.get("suite") and r.get("model") == before.get("model")
            ),
            None,
        )
        if after is None or before.get("suite") == "injection":
            continue
        hb = before.get("by_difficulty", {}).get("hard", {})
        ha = after.get("by_difficulty", {}).get("hard", {})
        rows.append(
            f"| {before['suite']} | `{before['model']}` "
            f"| {before['correct']}/{before['n']} ({before['accuracy']:.1%}) "
            f"| **{after['correct']}/{after['n']} ({after['accuracy']:.1%})** "
            f"| {_frac(hb)} | {_frac(ha)} "
            f"| {_latency(before)} | {_latency(after)} |"
        )
    return [*out, *rows, ""] if rows else []


def _breakdown(run: dict[str, Any]) -> list[str]:
    out = [f"### `{run['model']}` on the {run['suite']} suite — breakdown", ""]
    if by_diff := run.get("by_difficulty"):
        out += ["**By difficulty**", ""]
        out += ["| difficulty | correct/n |", "|---|---:|"]
        for key in ("easy", "medium", "hard"):
            if key in by_diff:
                out.append(f"| {key} | {_frac(by_diff[key])} |")
        out.append("")
    if by_tag := run.get("by_tag"):
        out += ["**By tag**", ""]
        out += ["| tag | correct/n |", "|---|---:|"]
        for key, stats in sorted(by_tag.items()):
            out.append(f"| {key} | {_frac(stats)} |")
        out.append("")
    if (warmup := run.get("warmup_ms")) is not None:
        out += [
            f"**Warm-up** before the first case: {warmup / 1000:.1f}s. It depends on what the "
            "model server already holds: loading the model and reading the prompt from cold "
            "takes about three minutes on this CPU (DECISIONS.md D37).",
            "",
        ]
    if run.get("repaired"):
        out += [
            f"**Repair loop:** {run['repaired']} answer(s) needed at least one repair; "
            f"{run['repaired_correct']} of them ended correct.",
            "",
        ]

    outcomes = run["_outcomes"]
    correct_conf = [o["confidence"] for o in outcomes if o["correct"]]
    wrong_conf = [o["confidence"] for o in outcomes if not o["correct"]]
    if correct_conf and wrong_conf:
        out += ["**Does the confidence score discriminate?**", ""]
        out += ["| answers | n | mean confidence |", "|---|---:|---:|"]
        out.append(f"| correct | {len(correct_conf)} | {_mean(correct_conf):.2f} |")
        out.append(f"| wrong | {len(wrong_conf)} | {_mean(wrong_conf):.2f} |")
        out += [
            "",
            "A gap here means the score carries signal — wrong answers really do",
            "score lower. It is still **not** a calibrated probability (see",
            "`DECISIONS.md` D17); with this few cases it is an observation, not a",
            "claim about the general case. Every signal is structural (did it parse,",
            "run, return rows, need a repair), so a wrong answer that is a well-formed",
            "query returning plausible rows scores like a right one.",
            "",
        ]

    failures = [o for o in outcomes if not o["correct"]]
    if failures:
        out += ["**Failures** (✓ = right answer with extra columns)", ""]
        out += ["| case | why |", "|---|---|"]
        for f in failures:
            mark = " ✓" if f.get("correct_relaxed") else ""
            out.append(f"| `{f['case_id']}`{mark} | {_failure_reason(f)} |")
        out.append("")
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=REPO_ROOT / "docs" / "results.md")
    args = parser.parse_args()

    runs = load_runs()
    baseline = load_runs(BASELINE) if BASELINE.is_dir() else None
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(runs, baseline), encoding="utf-8")
    print(f"wrote {args.out} from {len(runs)} run(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
